### ISSUE TITLE
Shape.Box is placed strangely

### ISSUE THREAD

**Issue by kag0** [PurpleKingdomGames/indigo#137]
When you create a `Box`, it is rendered with its center on the top left of the original dimensions used to create it.

relevantly:

```scala
lazy val position: Point = dimensions.position - (Point(square) / 2) - (stroke.width / 2)
```

I'm wondering if a box shape is really needed, or if box-specific constructors for a `Polygon` would suffice. 

```scala
Shape.Polygon(myRectangle.corners, ..., ...)
```

works identically in place of the broken

```scala
Shape.Box(myRectangle, ..., ...)
```

**Comment by davesmith00000** [comment]
Thank you for the feedback and for taking the time to raise the issue - I have wondered about this myself. Let me deconstruct it a little bit though to give you some context and see what you think.

I made a Box shape specifically because I thought it was likely to be one of the most common use cases. The process used to render a box is different from a polygon, a box has more efficient data transfer, its slightly more cacheable, and significantly less computationally expensive. So currently I'm inclined to keep box as it's own thing _as long as_ it can be made to work more pleasingly. The caveat is important.

The area on the screen the box takes up is a square - all the shapes are draw in perfect squares in fact. This seems odd but if the area is a not square then you end up with squashed borders and weird looking corners and so on, because the UV's have a funny aspect ratio. It's a bit of rendering implementation detail that is leaking - I should have hidden it better - I can see that detail has no business being on the API*.

>*As an aside, one of the things I wrestle with a bit is that for the first 4 years of Indigo's life, I could make crude things like this and leave them to mature for a while in private in their imperfect state - and then come back to them with fresh eyes - that's more difficult now. :-)

So two questions remain:

1) If box had behaved as you expected - would you have noticed the stuff above?

I suspect probably not..

2) Is the positioning of box around its origin weird?

Yes it might be, I think it feels wrong. Technically... technically... drawing the box around its origin is precisely correct - that's literally how the maths works. I look at Circle, which is position and radius - again centred around its origin and wonder if that feels right? Circle seems reasonable, Box less so?

So, if we hide the square bounds information somehow so that the user gets a boundary they expect, and we make the box appear starting from the top-left (like everything else), would that be better do you think?

**Comment by kag0** [comment]
Thanks for the thoughtful response!

1. I don't think I'd have noticed that box was really square under the hood if it looked like a rectangle on the screen
2. I think positioning the box from the top left (by default) seems natural, given a) how `Graphic`s behave and b) that you can change the reference point

Particularly, with the current API I'm not sure how the ref and the position relate. I would expect that the position would be the top left of the dimensions adjusted by the ref (ie. dimensions.topLeft + size/2 to get a centered position). Circle would be a bit less surprising to have the origin in the center (or maybe I'd expect the origin to be top left with a ref defaulted to the center). But then it's very surprising that a `Polygon` behaves differently than a `Box`, which I would assume is just a performance optimized `Polygon` with four sides at 90* angles.

**Comment by davesmith00000** [comment]
Good stuff, yes I'm with you. 👍

**Comment by davesmith00000** [comment]
Check list for me to work through:

- [ ] Shapes take up a square space but this shouldn't be apparent to the user:
  - [ ] Make the SceneProcessor calculate the square bounds
  - [ ] Report accurate bounds when calling `.bounds` on the shape
- [ ] Box position should default to top left like `Graphic`, not the center like `Circle`

**Comment by davesmith00000** [comment]
Here is the PR for the fix: https://github.com/PurpleKingdomGames/indigo/pull/146

**Comment by davesmith00000** [comment]
So in summary:

1. Box's start top left
2. All shapes `.bounds` call now gives the real bounds (including borders).
3. The rendering detail of the screen space being square is now hidden.
4. Ref points still work as expected.

**Comment by davesmith00000** [comment]
Fixed, will be in the next release.
