### ISSUE TITLE
Indigo game only ever receives a single ViewportResize event.

### ISSUE THREAD

**Issue by Sintrastes** [PurpleKingdomGames/indigo#334]
It seems that in Indigo 0.12.0 (on Windows, in Electron), my game is no longer receiving `ViewportResize` events.

A single `ViewportResize` event is emitted when Indigo is done loading the game initially, but no such events are emitted when manually resizing the Electron window, or toggling fullscreen mode.

**Comment by davesmith00000** [comment]
This might just be that the support js scripts that tell the canvas to resize when the window is resized as using the wrong canvas name or something.

A simple test:
Open the inspector (in electron) and use it to resize the canvas element - do you get the resize event?

**Comment by Sintrastes** [comment]
Yeah, that gives the resize event.

**Comment by davesmith00000** [comment]
It's an unfortunate oversight follow the canvas renaming work, the problem is here:

https://github.com/PurpleKingdomGames/indigo/blob/master/indigo-plugin/indigo-plugin/src/indigoplugin/templates/SupportScriptTemplate.scala#L25

Compared to...

<img width="485" alt="image" src="https://user-images.githubusercontent.com/908709/153962836-a7248cf9-280c-46a3-a719-bec07cd1bb42.png">

**Comment by davesmith00000** [comment]
I think I'll try and do the fix for this and push out another release since most people won't have been affected yet.
