### ISSUE TITLE
Ability to stop a launched game

### ISSUE THREAD

**Issue by sjrd** [PurpleKingdomGames/indigo#337]
After having `launch`ed an `IndigoDemo` (or `IndigoGame`), I would like to eventually be able to *stop* it. This is in the context of embedding the game inside a larger page, where other controls might decide to unmount the div/canvas of the game.

**Comment by davesmith00000** [comment]
So I think there's three things to do:

1. Expose some sort of `halt` method on the api next to `launch`.
2. If halt has been called, stop `tick` from requesting a new animation frame.
3. When halt is called, remove the canvas event listeners so that, in the unlikely event that someone has stopped the game but not removed the canvas, we don't accumulate events in the queue.
