### ISSUE TITLE
Lighting is not filled with its Material

### ISSUE THREAD

**Issue by AraneusRota** [PurpleKingdomGames/indigo#353]
Occurs when creating a Graphic using a Material.Bitmap with lighting and you try to fill it using either FillType.Tile or FillType.Stretch. Then the lighting (e.g. the normal or emissive map) behaves exactly like it wasn't filled (the texture is still filled normally). 

An example how that bug looks using FillType.Stretch. The texture is stretched but the normal (reflections) and emissive (red cross) map are not stretched accordingly:
https://user-images.githubusercontent.com/44680457/159352442-c103e744-9324-43ba-8be7-d9a6cb2030e1.mp4

Here is some code which produces this bug: https://github.com/AraneusRota/birdigo/blob/03bc398dd145e3f6c766f976772541e5a028af27/src/main/scala/violetempiregames/scenes/view/ObstaclesView.scala#L11-L20

**Comment by davesmith00000** [comment]
Replicating the problem:

This is the sandbox lighting scene, it produces a grid of graphics, and they all work as expected.

![image](https://user-images.githubusercontent.com/908709/169654053-29301eed-8fe8-44a1-a588-0346caf3e958.png)

A single graphic also works as expected of course...

![image](https://user-images.githubusercontent.com/908709/169654120-9495a1cf-2a7b-4136-af8f-a84d156044db.png)

...but stretching that graphic by changing the material `FillType` to `Stretch` and the crop to the screen size shows problems. Here you can see the emissive hasn't respected the stretch at all, and in fact none of the other textures have either other than diffuse, which is why it looks so smooth.

![image](https://user-images.githubusercontent.com/908709/169654226-696aa903-26b6-4c5e-8f6a-dcdd24a65c6a.png)

Finally switching the fill type to `Tile` shows a similar story, the one in the top left looks just fine, but all the others are too smooth and have lost the emissive (the green screen display). This is the behaviour reported in the bug.

![image](https://user-images.githubusercontent.com/908709/169654262-45ceef0a-5b14-4ab9-96d9-9c7ab10da588.png)

**Comment by davesmith00000** [comment]
Making progress
![image](https://user-images.githubusercontent.com/908709/169655554-932d2a3e-38a4-4d1e-a982-b7f154bf29c9.png)
