### ISSUE TITLE
Batch is not sound on `head` and other remarks

### ISSUE THREAD

**Issue by lomigmegard** [PurpleKingdomGames/indigo#377]
Hi!

I stumbled by chance on the new `Batch` collection added recently in this library. After a quick look at the implementation, it exhibits a few weaknesses and at least a couple bugs. Using a single ticket to collect my thoughts on it, a PR might follow if I find the time. 

---

`Combine` case is not guaranteed to have non-empty children, whereas `head` and `headOption` assume so. At the same time `isEmpty` indicates the implementation may allow non-empty children.

This test fails:
```
assert(Batch(Batch.Empty, Batch(1, 2, 3)).head == 1)
// java.util.NoSuchElementException: Batch.Empty.head
```

Two approaches:
- (a) ensure the children of `Combine` are never empty by using the `++` everywhere. Can be error-prone but simple enough to implement, might be worth adding implementation comments on the design decision. Will make the `isEmpty` always false.
- (b) allow empty children and fix `head` and `headOption` accordingly.

---

The `mkString` throws an exception on the empty cases.
The `mkString(" ")` also adds a trailing separator in the case of single element, which is not expected?

Failing tests:
```
test("mkString") {
  assert(Batch.Empty.mkString == "")
  assert(Batch(1).mkString(" ") == "1")
}
```

--- 

The memoization in `_jsArray` is simple enough, but a bit arbitrary as some methods will use it, and some won't. It could be interesting to try to leverage this memoization in the `Wrapped` and `Combine` cases, actually making sure it's computed only once and short-circuiting all the methods on it. To simplify the `Batch` implementation it could also be an option to drop the `Empty` and `Singleton` (replaced with `Wrapped`), without any performance impact.

---

The `catch { _ => false }` fallback in equality check is not idiomatic and may have serious performance impact.

---

I am not sure on how `js.Array` is implemented, but the unapply on `::` might have misleading performance, splitting the array over and over again in the `tail`?

**Comment by lomigmegard** [comment]
Let me know what you think about it, and sorry for the long post 😉 

I can do a few PRs tackling points one by one, if I get this project setup working in IntelliJ !

**Comment by davesmith00000** [comment]
Hi there!

Thank you for taking an interest. I'd be very happy to receive help making `Batch` better. 😄 

Batch is definitely in a sort of rough and ready state, I was slightly nervous about boldly releasing it but the performance improvement was hard to ignore.

Some of your notes definitely seem valid and are clearly oversights on my part, thinking of the comments on `catch` and empty `mkString` in particular. Others I'm less certain that we're on the same page over, but would love to discuss further either here (on this issue or separate ones) or on [Discord](https://discord.gg/b5CD47g). Administratively, it's easier in terms of generating release notes if everything has an issue and a PR - but I'm pretty relaxed about these things.

The goals of batch are listed in the next few bullet points, and whatever improvements are made, it's important not to lose sight of these. We could decide that one or more of them is invalid but I'd want that to be a conscious choice.

- Improve construction speed since this is the primary thing we do with `Batch` in Indigo i.e. build lists of stuff rather than manipulate lists of stuff.
- Reduce friction with the core of the engine which is `js.Array` based.
- To be roughly as performant as `js.Array` for most operations (which is why it's really quite a thin layer over `js.Array`)
- Secondary goal: To _feel_ a bit like a drop-in replacement for `List` (`head` is not guaranteed here either for instance), but not at the expense of the first three goals.

I'm totally open to all efforts to make it better though! For more context, here is the original [PR](https://github.com/PurpleKingdomGames/indigo/pull/368).

Side note: Don't know if you noticed but there is also a `NonEmptyBatch`?

**Comment by davesmith00000** [comment]
I mention the goals because I think it would be easy to fall into the trap of making a type that behaves as 'correctly' or be as full featured as List or NonEmptyList, but inadvertently also end up with the same performance characteristics - which is not the point of Batch. Hope that makes sense.

**Comment by lomigmegard** [comment]
Hey thanks for the quick reply, Saturday is definitely for side projects 😄 

Your listed goals make total sense for sure! And I will open dedicated issues and tasks if I find the time to work on them a bit more, it's easier to show what I meant with some draft code.

Cheers

**Comment by davesmith00000** [comment]
Working on this a bit here after I found bug #388: https://github.com/PurpleKingdomGames/indigo/pull/389

**Comment by davesmith00000** [comment]
Benchmarks from removing `Empty` and `Singleton`. Removed on the left, original on the right.

![Screenshot 2022-07-04 at 01 31 11](https://user-images.githubusercontent.com/908709/177063052-9bac4510-68a5-4405-99e4-0f86b7e7f26c.png)

Very little in it (noting the error margins). With them removed, concat is very slightly slower, but toJsArray is faster. So all in all, I'm going to remove them because it makes the implementation simpler.

Thanks for the suggestion. 😄

**Comment by davesmith00000** [comment]
I believe I've answered most of this in the work that is now in `main`, very helpful - thank you! Would be happy to re-open if you think I've missed anything or address individual issues on a case by case basis.
