### ISSUE TITLE
LineSegment.closestPointOnLine only works for positive gradients.

### ISSUE THREAD

**Issue by mattyjbrown** [PurpleKingdomGames/indigo#390]
```
import indigo.*
import indigoextras.geometry.{LineSegment, Vertex}

//Considering the diagonals of the unit square
val zero_zero = Vertex(0, 0)
val one_one   = Vertex(1, 1)
val one_zero  = Vertex(1, 0)
val zero_one  = Vertex(0, 1)

//This point already sits on all of those lines, because it's the centre
val testPoint = Vertex(0.5, 0.5)

//Only the first one returns testPoint, all other answers are clamped incorrectly
LineSegment(zero_zero, one_one).closestPointOnLine(testPoint).contains(testPoint) //true
LineSegment(one_one, zero_zero).closestPointOnLine(testPoint).contains(testPoint) //false
LineSegment(one_zero, zero_one).closestPointOnLine(testPoint).contains(testPoint) //false
LineSegment(zero_one, one_zero).closestPointOnLine(testPoint).contains(testPoint) //false

//The problem is with the use of Vertex.clamp:
extension (line: LineSegment) {
  def unclampedClosestPointOnLine(to: Vertex): Option[Vertex] =
    import line._
    val a   = end.y - start.y
    val b   = start.x - end.x
    val c1  = a * start.x + b * start.y
    val c2  = -b * to.x + a * to.y
    val det = a * a - -b * b

    if det != 0.0 then
      Some(
        Vertex(
          x = (a * c1 - b * c2) / det,
          y = (a * c2 - -b * c1) / det
        )
      )
    else None
}

//All correctly return Some(testPoint)
LineSegment(zero_zero, one_one).unclampedClosestPointOnLine(testPoint).contains(testPoint) //true
LineSegment(one_one, zero_zero).unclampedClosestPointOnLine(testPoint).contains(testPoint) //true
LineSegment(one_zero, zero_one).unclampedClosestPointOnLine(testPoint).contains(testPoint) //true
LineSegment(zero_one, one_zero).unclampedClosestPointOnLine(testPoint).contains(testPoint) //true
```
The problem is that `Vertex#clamp(min: Vertex, max: Vertex)` assumes that min is the smallest X AND the smallest Y.

Is that problem with `LineSegment`'s USAGE of `Vertex#clamp`, or with the implementation of `Vertex#clamp`?

My understanding of `Vertex#clamp` is that it's clamping a vertex to inside the rectangle made by the two vertices it is passed. At the moment this only works if you give it a bottom left and a top right.

Should `Vertex#clamp` rationalise the coordinates it is passed? Or should `LineSegment` rationalise its `start` and `end` before calling `Vertex#clamp`?

I've done a quick search through Indigo and I think Vertex is the only class which supports clamping by coordinates rather than by absolute values, and this is only called by this `LineSegment` algorithm at the moment, so can probably get away with either solution.

**Comment by davesmith00000** [comment]
Well spotted, thanks for reporting @mattyjbrown. :+1: 

Yes you're quite right. I've reproduced your test case above.

There's a sorting chin scratching question of "What does clamping a `Vertex` even mean?" that you could get lost in, however I added it so that it behaved (hopefully) like [GLSL's clamp function](https://thebookofshaders.com/glossary/?search=clamp), albeit, I've allowed you to pass in a top-left/bottom-right pair of `Vertex`'s too - and maybe, just maybe - that's really weird. :smile: 

But I think what I'm going to do is fix the `closestPointOnLine` function. Your solution of removing the `clamp` call fixes your test case but breaks another, so I think what's needed is another clamp inside that function that rationalises the inputs (as you alluded to above).

I'll give it a shot.

**Comment by davesmith00000** [comment]
A quick fix, this works:

`clamp(start.min(end), start.max(end))`

I'll see if it's worth unrolling all of that though.
