### ISSUE TITLE
Missing stroke with Shape.Polygon

### ISSUE THREAD

**Issue by JPonte** [PurpleKingdomGames/indigo#420]
Seems like there is an issue with the stroke rendering when there are vertical or horizontal lines in `Shape.Polygon`. This seems to happen only when stroke weight is 1.

For example, this code:
```scala
    val testPolygon = Shape
      .Polygon(
        Batch(Point(0, 0), Point(64, 32), Point(64, 64), Point(0, 32)
        ),
        Fill.Color(RGBA.SlateGray),
        Stroke.apply(1, RGBA.White)
      ).moveTo(10, 10)

    val testPolygon2 = Shape
      .Polygon(
        Batch(Point(0, 0), Point(0, 64), Point(64, 64), Point(64, 0)
        ),
        Fill.Color(RGBA.SlateGray),
        Stroke.apply(1, RGBA.White)
      ).moveTo(100, 10)

    Outcome(
      SceneUpdateFragment(
        testPolygon, testPolygon2
      )
    )
```
produces this:
![image](https://user-images.githubusercontent.com/2581298/191609378-eb702776-b40a-4a67-aa8c-981d64c2752c.png)

**Comment by davesmith00000** [comment]
This turned out to be two things:

1. The old bug of 1px stroke sitting perfectly on a line. (I hadn't applied it to polygon...)
2. The bounds calculation not giving enough room for the border and cutting it off.

Notice the perfectly square one is still imperfect (bottom right corner), but it's a lot better. However, there will always be rounding issues with polygons / shapes and pixel art, so I'm not too concerned. We have a box shape for perfect boxes for exactly this reason! 😄

![image](https://user-images.githubusercontent.com/908709/192136428-4cdcbb4f-55f2-42c4-83c9-205cb23f7a0c.png)
