### ISSUE TITLE
TextureAtlas Loading image data is insecure

### ISSUE THREAD

**Issue by laurensdv** [PurpleKingdomGames/indigo#52]
Hello,

after loading succesfully images in the indigo demo application:
`[Log] [INFO] [Indigo] [Image] Loading assets/dots.png (mygame-indigo_demo-fastopt.js, line 75157)`
`[Log] [INFO] [Indigo] [Image] Success assets/dots.png (mygame-indigo_demo-fastopt.js, line 75157)`
`[Log] [INFO] [Indigo] Asset load complete (mygame-indigo_demo-fastopt.js, line 75157)`
`[Log] [INFO] [Indigo] Creating atlases. Max size: 4096x4096 (mygame-indigo_demo-fastopt.js, line 75157)`

I get the following error, right after the atlas creation instruction:
`Unable to get image data from canvas because the canvas has been tainted by cross-origin data.
(anonymous function) — TextureAtlas.scala:226
(anonymous function) — TextureAtlas.scala:248
(anonymous function) — TextureAtlas.scala:267:110
(anonymous function) — AnonFunctions.scala:27
create__sci_List__F1__F2__Lindigo_platform_assets_TextureAtlas — TextureAtlas.scala:38
createTextureAtlas__Lindigo_platform_assets_AssetCollection__s_util_Try — List.scala:245
initialise__s_util_Try — Platform.scala:39
(anonymous function) — GameEngine.scala:142
(anonymous function) — GameEngine.scala:107
foreach__F1__V — Try.scala:260
run__V — Promise.scala:444
scala$scalajs$concurrent$QueueExecutionContext$PromisesExecutionContext$$$anonfun$execute$2__jl_Void__jl_Runnable__sjs_js_$bar — QueueExecutionContext.scala:52
promiseReactionJob
$p_jl_JSConsoleBasedPrintStream__doWriteLine__T__V — System.scala:389`

See:
https://github.com/PurpleKingdomGames/indigo/blob/b3bb061b609f819358fd361e3bc58233c8d9c3be/indigo/indigo-platforms/src/main/scala/indigo/platform/assets/TextureAtlas.scala#L226

The issue occurs when trying to run it in an ios or android cordova container. My impression is that it has to do with recent restriction being put on loading files through file:/// protocol.

How could I resolve this issue? Is this something that will be addressed, or is it something that can be workaround, e.g. hosting the images on a CDN rather than including them in the app assets?

**Comment by davesmith00000** [comment]
Hi @laurensdv, thank you submitting the issue. I'll need some time to look into it but I'll try and give it a once over later today/tonight and come back to you.

**Comment by davesmith00000** [comment]
We do get some warnings in Electron too:

```
1. (electron) Security Warning: webFrame.executeJavaScript was called without worldSafeExecuteJavaScript enabled. This is considered unsafe. worldSafeExecuteJavaScript will be enabled by default in Electron 12.

2. Electron Security Warning (Insecure Content-Security-Policy) This renderer process has either no Content Security
    Policy set or a policy with "unsafe-eval" enabled. This exposes users of
    this app to unnecessary security risks.
For more information and help, consult
https://electronjs.org/docs/tutorial/security.
This warning will not show up
once the app is packaged.
```

**Comment by davesmith00000** [comment]
Thank you for the detailed bug report.

Cards on the table, I haven't tried running Indigo on mobile before using Cordova, and come to that, I'm having great difficulty running any of this through Cordova on either iOS, Android, or OSX. I get different errors to you! :-)

Cordova for browser and Electron work just fine, incidentally.

Are you running this emulated or on your own device(s)?

Indigo doesn't load anything from file, it's all served from a http server, but this seems very relevant:

https://developer.mozilla.org/en-US/docs/Web/HTML/CORS_enabled_image

> If the source of the foreign content is an HTML `<img>` or SVG `<svg>` element, attempting to retrieve the contents of the canvas isn't allowed. (...) Calling any of the following on a tainted canvas will result in an error (...) 1. Calling `getImageData()` on the canvas's context

Which is what happens on the line of code you highlighted.

It looks like the solution is quite straight forward, essentially just to configure Cordova's CORS information and then find a way to supply the same to Indigo to add as a `.crossOrigin` field on the HTML image element.

The catch is that I haven't figured out how to reproduce the problem in order to be able to test a fix. A fudge might be to add `.crossOrigin = "Anonymous"` with the `*` CORS setting as they do in the docs above, but again I can't test it.

I'll keep trying to replicate the problem, but this might take a while.

If you're up for it (as long as you're not a windows user), you could attempt to do a local build of Indigo yourself, add the property, do a local publish and try it on your demo app. There's a `build.sh` file in the root that does everything. If you do try it, you will need to have the glsl validator installed. Let me know if you have a go.

In terms of a workaround, I suspect there isn't one at the moment I'm afraid. I would like to get this fixed but I can't promise a quick turnaround.

**Comment by laurensdv** [comment]
Hello,

Making progress, at least my impression.

- I managed to build the indigo code from github with build.sh, I am running on OS X (otherwise no iOS building obviously). So if you @davesmith00000 would like me to check possible fixes or tweaks, I can test it in my setup. I would just need to know how you recommend me to link the indigo built (after build.sh) from github in my indigo project.
- I have updated to the latest version of the cordova iOS plugin (@6.1.1)
- Note also with previous version I had to add in the cordova platforms > ios > www > index.html the following in the head: `<script src="cordova.js"></script>`

Now it seems the built is at a point where the application is loading correctly and elements in the canvas are being loaded (at least behind the scenes, more details below).

```
[Log] Device is Ready (cordova.js, line 1413)
[Log] [INFO] [Indigo] Starting Indigo (cordova.js, line 1413)
[Log] [INFO] [Indigo] Configuration:  (cordova.js, line 1413)
[Log] Standard settings (cordova.js, line 1413)
[Log] - Viewpoint:      [412, 896] (cordova.js, line 1413)
[Log] - FPS:            60 (cordova.js, line 1413)
[Log] - frameRateDelta: 16 (view updates stop at: 32, model at: 48 (cordova.js, line 1413)
[Log] - Clear color:    {red: 0, green: 0, blue: 0, alpha: 1} (cordova.js, line 1413)
[Log] - Magnification:  2 (cordova.js, line 1413)
[Log]  (cordova.js, line 1413)
[Log] Advanced settings (cordova.js, line 1413)
[Log] - Rendering technology:        WebGL 2.0 (will fallback to WebGL 1.0) (cordova.js, line 1413)
[Log] - AntiAliasing enabled:        false (cordova.js, line 1413)
[Log] - Render batch size:           256 (cordova.js, line 1413)
[Log] - Disabled skip model updates: false (cordova.js, line 1413)
[Log] - Disabled skip view updates:  false (cordova.js, line 1413)
[Log]  (cordova.js, line 1413, x2)
[Log] [INFO] [Indigo] Attempting to load assets (cordova.js, line 1413)
[Log] [INFO] [Indigo] Loading 3 assets (cordova.js, line 1413)
[Log] [INFO] [Indigo] [Image] Loading assets/boxy_font_small.png (cordova.js, line 1413)
[Log] [INFO] [Indigo] [Image] Loading assets/dots.png (cordova.js, line 1413)
[Log] [INFO] [Indigo] [Image] Loading assets/destructible_objects.png (cordova.js, line 1413)
[Log] [INFO] [Indigo] [Image] Success assets/boxy_font_small.png (cordova.js, line 1413)
[Log] [INFO] [Indigo] [Image] Success assets/dots.png (cordova.js, line 1413)
[Log] [INFO] [Indigo] [Image] Success assets/destructible_objects.png (cordova.js, line 1413)
[Log] [INFO] [Indigo] Asset load complete (cordova.js, line 1413)
[Log] [INFO] [Indigo] Creating atlases. Max size: 4096x4096 (cordova.js, line 1413)
[Log] [INFO] [Indigo] Atlas details: (cordova.js, line 1413)
[Log] Number of atlases: 1 (cordova.js, line 1413)
[Log] Atlases: [ (cordova.js, line 1413)
[Log]   Atlas [atlas_0] [2048] contains images: destructibleObjects, smallFontName, dots (cordova.js, line 1413)
[Log] ] (cordova.js, line 1413)
[Log]    (cordova.js, line 1413)
[Log] [INFO] [Indigo] Starting world events (cordova.js, line 1413)
[Log] [INFO] [Indigo] Starting renderer (cordova.js, line 1413)
[Log] [INFO] [Indigo] This browser does not appear to support WebGL 2.0, trying WebGL 1.0. (cordova.js, line 1413)
[Log] [INFO] [Indigo] Using WebGL 1.0. (cordova.js, line 1413)
[Log] [INFO] [Indigo] Pixel vshader compiled: true (cordova.js, line 1413)
[Log] [INFO] [Indigo] Pixel fshader compiled: true (cordova.js, line 1413)
[Log] [INFO] [Indigo] Lighting vshader compiled: true (cordova.js, line 1413)
[Log] [INFO] [Indigo] Lighting fshader compiled: true (cordova.js, line 1413)
[Log] [INFO] [Indigo] Merge vshader compiled: true (cordova.js, line 1413)
[Log] [INFO] [Indigo] Merge fshader compiled: true (cordova.js, line 1413)
[Log] [INFO] [Indigo] Game initialisation succeeded (cordova.js, line 1413)
[Log] [INFO] [Indigo] Starting main loop, there will be no more info log messages. (cordova.js, line 1413)
[Log] [INFO] [Indigo] You may get first occurrence error logs. (cordova.js, line 1413)However, in the emulator display nothing is being shown, but also: no more errors are being displayed.
```

It may have to do with the following article: https://cordova.apache.org/howto/2020/07/18/uiwebview-warning.html.
My guess is that maybe on the right place in the generated JS code the following should come on the image paths, 
maybe with a if check to se if a wkwebview is existing: `window.WkWebView.convertFilePath('your/file/path');`

Or maybe something is wrong with the canvas position/sizeing (is it off screen)? In safari debug of the web view, the div / canvas element is not being marked on the emulator screen. But in the canvas elements debug, the WebGL screen seems to be correctly generated.
```html
...
<div id="indigo-container"><canvas id="indigo" width="412" height="896"></canvas></div>
...
```

![image](https://www.dropbox.com/s/ey7mnsk7rwwa9q6/Screen%20Shot%202020-09-10%20at%2010.38.08%20AM.png?raw=1)

Or something else entirely of course...

**Comment by davesmith00000** [comment]
I'm still struggling. :-)

I have made progress in that I did manage to reproduce your original problem, but I'm now have Cordova build issues. I'll keep plugging away at it.

I'm not quite sure that you mean by "linking". If you've run the build script than your `~/.ivy2/local/` should contain a freshly minted version of Indigo, currently `0.3.1-SNAPSHOT`, so you just need to replace the `0.3.0` in your various build files with the new version number and rebuild your game.

The place where I expected to need to add the `crossOrigin` attribute was in the `AssetLoader` class where we make an `html.Image` to load the data into. However I tried that earlier and hit a problem, which is that the `html.Image` type def does have a `crossOrigin` field on it. I think you should be able to set it using `setAttribute` though.

***However! Before you do any of that.***

I think I've realised that I was fundamentally mistaken about how Cordova works, and I suspect you're on the right path and that I'm wrong. :-)

Indigo is supposed to be run from a local web server, and because Cordova has a `www` folder I put 2 and 2 together and got 5 - assuming that's what it was doing. But I think what you're saying is that it's actually just loading local files in a browser. Which wouldn't work easily. Because CORS.

So there's two solutions, assuming I'm not on the right path:

1. Do the thing you're suggesting and figure out how to make the paths acceptable.
2. Run a http server - and there's a plugin for that that says:

> For security reason, browser does not support local AJAX calls. It's big bottle neck to deploy HTML5 games to Cordova platform.

https://github.com/floatinghotpot/cordova-httpd

Sounds promising, and wouldn't require you to modify Indigo. What do you think?

If we get this working I might try and bake it into the plugin somewhere to help the next poor soul out...

**Comment by laurensdv** [comment]
Hello, 

Some further progress to report: indeed it must run from 'kinda server', most importantly it mustn't behave CORS. 
Still working with 0.3.0 Indigo, so no changes (yet).

Near the bottom of the article, https://cordova.apache.org/howto/2020/07/18/uiwebview-warning.html, it turns out that at Cordova they were thinking the same and they built in a solution in the 6.1.0 version of the iOS platform (no need for cordova wkwebview plugin!).
And also, September 9, Cordova 10.0 was released and I updated to that version now.

Adding: `
<preference name="scheme" value="app" />
<preference name="hostname" value="localhost" />`
to the platform iOs configuration.

results in:

![screen](https://www.dropbox.com/s/vx78w4j5jpgc46b/Screen%20Shot%202020-09-11%20at%209.18.03%20AM.png?raw=1)

Note (red box marked) that all files are now being served through some kind of Cordova built-in hosting mechanism.

```xml
    <preference name="AutoHideSplashScreen" value="true" />
    <platform name="ios">
        <allow-intent href="app:*" />
        <allow-intent href="itms:*" />
        <allow-intent href="itms-apps:*" />
        <preference name="scheme" value="app" />
        <preference name="hostname" value="localhost" />
    </platform>
```

Note: a white screen was shown as splash screen (not the default cordova splash grey with the icon - but that's I guess another issue) that didn't go away before, hence `<preference name="AutoHideSplashScreen" value="true" />`

Next steps:
- Find a way to automatically adapt the canvas to fill the screen (full screen mode?): either in Cordova, or as Indigo configuration -> I noticed another topic was opened here in that regard(?). Also maybe combine with a way to align the configured screen size for the different cordova target platforms to the viewport / magnification settings in Indigo (sometimes resize to fit screen, sometimes go to windowed mode...).
- Debug the (mouse/touch?) inputs, at the moment not much happens when clicking around while it does work fine in the indigo electron built or the cordova browser built.

Can you reproduce and get to the same point?

**Comment by davesmith00000** [comment]
Brilliant! Well done!

**Inputs**
I don't know much about this, but Indigo doesn't currently support touch events (we can totally add them though - happy to help!). In a browser on mobile, the browser will interpret a touch event as a mouse click. I have no idea if that same interpretation happens on phones or phone emulators.

**Resizing**
My expectation is that there's no need to touch Indigo for this. Indigo supports two useful things here:

1. Flags - a JS object passed to the constructor (the type ends up being `Map[String, String]` for boring reasons) which you could use to inspect the device and supply things like an appropriate magnification.

2. `ViewportResize` events. These are triggers when the canvas is resized. So want you'd have to do is a bit of CSS wizardry to make the canvas fill the available page space, listen to the events, and adjust your rendered view accordingly.

**Comment by davesmith00000** [comment]
If possible, I'd love to get access to your project (or a version of it) to see if it builds correctly for me too. In the meantime I shall keep plugging away to see if I can get to the same point.

I was just talking to @JonasAckermann on our Discord channel about the fact that Indigo doesn't autosize to fill the electron window, by some coincidence. I'd like to avoid getting into maintaining complex packaging set ups, but it may be worth adding the resizing to the electron build (if it works for Electron it should hopefully work for Cordova), and then also seeing if we can add a basic Cordova project as an output of the plugin - might be a pain but we can try.

**Comment by laurensdv** [comment]
Great, you can check out my hello world indigo project. It shows a chest box that should open and close when you click on it.  That's it for now :-). It should include everything needed for a built, but you need to follow cordova instructions (mainly running `cordova prepare` before trying to build anything). 
https://github.com/laurensdv/helloworldindigo

Indeed, after taking a closer look and clicking more precisely. The mouseclick - which simulates a touch in the emulator - is being detected as a mouse click event, as it was in the electron built. So no issue there.

For what it is worth: Cordova has electron platform support as well (https://cordova.apache.org/docs/en/latest/guide/platforms/electron/). I don't know if there is any advantage/disadvantage going through cordova or not for getting an electron app. Anyway, it works without any additional configuration without issue - aside from the autosizing.
So I guess if the (re)sizing (to full screen) works in a browser windows, it should also be able to detect the 'device' size of a wkwebview in iOs. For the sizing, I am not sure what would be the recommendation for a 'one time' screen size check and adapt, so no on the fly adaptation, but that of course may be useful in browser windows...

See below side by side: cordova iOS and cordova Electron build.
![image](https://www.dropbox.com/s/hmch8021a1qew99/Screen%20Shot%202020-09-11%20at%202.56.08%20PM.png?raw=1)

**Comment by davesmith00000** [comment]
Cool, I'll give it a shot later.

**Comment by davesmith00000** [comment]
Just having a quick play with resizing as the window changes size. This isn't quite good enough but it illustrates the idea, you just need to add the following to the `index.html` file.

```html
  <script type="text/javascript">
    function resizeCanvas() {
      var c = document.getElementById("indigo");
      c.height = window.innerHeight;
      c.width = window.innerWidth;
    }

    window.onresize = resizeCanvas;
  </script>
```

The problems with that are:

1. It doesn't work until you're resized, i.e. the canvas is initially drawn at the wrong size, but you could solve that (probably) by passing the window's `innerWidth` and `innerHeight` as [Flags](https://indigoengine.io/docs/topics/boot-and-start-up#flags).
2. You get some unpleasant tearing in the graphics and the canvas adapts. So I think you'd want something a little smarter that only resizes the canvas once you stop resizing (after a delay?) rather than constantly.

**Comment by davesmith00000** [comment]
@laurensdv That's brilliant! Worked first time for me!

So really the only file we'd need to generate is the `config.xml` file, and provide instructions as to how to run it? Does that sound right to you?

**Comment by laurensdv** [comment]
A config.xml would be required indeed and also a package.json, the package.json would contain the correct version of any needed platforms and plugins that align with the config.xml.

See: https://cordova.apache.org/docs/en/latest/platform_plugin_versioning_ref/index.html

In the docs of cordova, it is expected that cordova is installed in global npm space.

**Comment by davesmith00000** [comment]
@laurensdv if you feel like it, you could take a look at: https://github.com/PurpleKingdomGames/indigo/pull/63

No pressure. :-)

**Comment by davesmith00000** [comment]
Basic Cordova support will be part of the plugins in the next release.
